freebsd_task:
  env:
    GOFLAGS: -mod=vendor
  
  freebsd_instance:
    image: freebsd-11-2-release-amd64
  
  install_script: pkg install -y go gcc git
  test_script: make test

linux386_task:
  container:
    matrix:
      - image: i386/golang:1.14
      - image: i386/golang:1.13
      - image: i386/golang:1.12
  test_script:
    -  go version
    -  uname -a
    -  make test
