freebsd_task:
  env:
    GOFLAGS: -mod=vendor
  
  freebsd_instance:
    image: freebsd-11-2-release-amd64

  install_script: pkg install -y go gcc git
  test_script: make test

linux386_task:
  container:
    image: i386/centos:7
  env:
    matrix:
      - GOVERSION: 1.12
      - GOVERSION: 1.13
      - GOVERSION: 1.14
  test_script:
    -  yum -y install wget make git gcc
    -  wget -q https://dl.google.com/go/go${GOVERSION}.linux-386.tar.gz
    -  tar -C /usr/local -xzf go${GOVERSION}.linux-386.tar.gz
    -  export PATH=$PATH:/usr/local/go/bin
    -  wget -q https://github.com/golang/go/archive/go1.14rc1.tar.gz
    -  tar -C /usr/ -xzf go1.14rc1.tar.gz
    -  export GOROOT_BOOTSTRAP=/usr/local/go1.4
    -  go env
    -  cd /usr/go-go1.14rc1/src
    -  ./all.bash
  ss_script:
    -  export PATH=$PATH:/usr/local/go1.4/bin
    -  go version
    -  uname -a
    -  make test
